# DeepSeek-Prover-V2 (non-CoT baseline) on miniF2F-rw valid.
prover: configs/models/deepseek-single-pass-baseline-vllm.yaml

dataset_path: data/minif2f-rw.jsonl
split: valid

dataset_name: minif2f-rw
experiment_id: deepseek-miniF2F-rw-valid-noncot

num_attempts: 64
batch_size: 64
