class: EnsembleLLMProver

parameters:
  ensemble_size: 4
  shuffle_seed: 0

  rewriting:
    class: RewritingCanonicalization
    parameters:
      project_root: .
      timeout_seconds: 90.0
      top_rewrites: 10
      sampling:
        max_per_step: 15
        depth: 2
        only_simplifying_rewrites: true
      reranking:
        type: shortest_states
      energy:
        type: theorem_surprise

  single_pass_prover:
    class: SinglePassProver
    parameters:
      llm:
        class: HFChatLLM
        parameters:
          model_name_or_path: deepseek-ai/DeepSeek-Prover-V2-7B
          max_new_tokens: 2000
          device_map: auto
          torch_dtype: bfloat16

      prompt_formatter:
        class: DeepSeekProverPromptFormatter
        parameters: {}

      project_root: .
      timeout_seconds: 120.0
